name: 'JSON Patch'
description: 'Patch the specified config file with the given operation'
inputs:
  file:  # id of input
    description: 'file to perform patch operation on'
    required: true
  output:
    description: 'output patched file in this format'
    required: true
    default: 'yaml'
  op:
    description: 'operation to perform'
    required: true
    default: "replace"
  path:
    description: 'JSON Path to the object to perform the operation on'
    required: true
  value:
    description: 'value to use in operation at the given path'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
